apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-backend
  template:
    metadata:
      labels:
        app: gateway-backend
    spec:
      containers:
      - name: gateway-backend
        image: giovannilopopolo98/pca-svm-gateway:latest
        ports:
        - containerPort: 8080
